- platform: template
  lights:
    lights_kitchen1:
      friendly_name: "부엌 조명 1"
      value_template: "{{ states('sensor.lights_kitchen').split('\n')[0] }}"
      turn_on:
        service: rest_command.light_control_room
        data:
          room_num: '1'
          unit_num: '1'
          control_action: 'on'
      turn_off:
        service: rest_command.light_control_room
        data:
          room_num: '1'
          unit_num: '1'
          control_action: 'off'        
          
    lights_kitchen2:
      friendly_name: "부엌 조명 2"
      value_template: "{{ states('sensor.lights_kitchen').split('\n')[1] }}"
      turn_on:
        service: rest_command.light_control_room
        data:
          room_num: '1'
          unit_num: '2'
          control_action: 'on'
      turn_off:
        service: rest_command.light_control_room
        data:
          room_num: '1'
          unit_num: '2'
          control_action: 'off'
    
    lights_kitchen3:
      friendly_name: "부엌 조명 3"
      value_template: "{{ states('sensor.lights_kitchen').split('\n')[2] }}" 
      turn_on:
        service: rest_command.light_control_room
        data:
          room_num: '1'
          unit_num: '3'
          control_action: 'on'
      turn_off:
        service: rest_command.light_control_room
        data:
          room_num: '1'
          unit_num: '3'
          control_action: 'off'          
          
    lights_livingroom1:
      friendly_name: "거실 조명 1"
      value_template: "{{ states('sensor.lights_livingroom').split('\n')[0] }}"
      turn_on:
        service: rest_command.light_control_living_room
        data:
          unit_num: '1'
          control_action: 'on'
      turn_off:
        service: rest_command.light_control_living_room
        data:
          unit_num: '1'
          control_action: 'off'
          
    lights_livingroom2:
      friendly_name: "거실 조명 2"
      value_template: "{{ states('sensor.lights_livingroom').split('\n')[1] }}"
      turn_on:
        service: rest_command.light_control_living_room
        data:
          unit_num: '2'
          control_action: 'on'
      turn_off:
        service: rest_command.light_control_living_room
        data:
          unit_num: '2'
          control_action: 'off'
          
    lights_livingroom3:
      friendly_name: "거실 조명 3"
      value_template: "{{ states('sensor.lights_livingroom').split('\n')[2] }}"
      turn_on:
        service: rest_command.light_control_living_room
        data:
          unit_num: '3'
          control_action: 'on'
      turn_off:
        service: rest_command.light_control_living_room
        data:
          unit_num: '3'
          control_action: 'off'
    
    lights_mainroom1:
      friendly_name: "안방 조명1"
      value_template: "{{ states('sensor.lights_mainroom').split('\n')[0] }}" 
      turn_on:
        service: rest_command.light_control_room
        data:
          room_num: '2'
          unit_num: '1'
          control_action: 'on'
      turn_off:
        service: rest_command.light_control_room
        data:
          room_num: '2'
          unit_num: '1'
          control_action: 'off'

    lights_mainroom2:
      friendly_name: "안방 조명2"
      value_template: "{{ states('sensor.lights_mainroom').split('\n')[1] }}" 
      turn_on:
        service: rest_command.light_control_room
        data:
          room_num: '2'
          unit_num: '2'
          control_action: 'on'
      turn_off:
        service: rest_command.light_control_room
        data:
          room_num: '2'
          unit_num: '2'
          control_action: 'off'
          
    lights_room3:
      friendly_name: "방3 조명1"
      value_template: "{{ states('sensor.lights_room3').split('\n')[0] }}"
      turn_on:
        service: rest_command.light_control_room
        data:
          room_num: '3'
          unit_num: '1'
          control_action: 'on'
      turn_off:
        service: rest_command.light_control_room
        data:
          room_num: '3'
          unit_num: '1'
          control_action: 'off'
          
    lights_room3:
      friendly_name: "방3 조명2"
      value_template: "{{ states('sensor.lights_room3').split('\n')[1] }}"  
      turn_on:
        service: rest_command.light_control_room
        data:
          room_num: '3'
          unit_num: '2'
          control_action: 'on'
      turn_off:
        service: rest_command.light_control_room
        data:
          room_num: '3'
          unit_num: '2'
          control_action: 'off'
          
    lights_room4:
      friendly_name: "방4 조명1"
      value_template: "{{ states('sensor.lights_room4').split('\n')[0] }}"      
      turn_on:
        service: rest_command.light_control_room
        data:
          room_num: '4'
          unit_num: '1'
          control_action: 'on'
      turn_off:
        service: rest_command.light_control_room
        data:
          room_num: '4'
          unit_num: '1'
          control_action: 'off'
          
    lights_room4:
      friendly_name: "방4 조명2"
      value_template: "{{ states('sensor.lights_room4').split('\n')[1] }}"
      turn_on:
        service: rest_command.light_control_room
        data:
          room_num: '4'
          unit_num: '2'
          control_action: 'on'
      turn_off:
        service: rest_command.light_control_room
        data:
          room_num: '4'
          unit_num: '2'
          control_action: 'off'

    lights_room5:
      friendly_name: "방5 조명1"
      value_template: "{{ states('sensor.lights_room5').split('\n')[0] }}"      
      turn_on:
        service: rest_command.light_control_room
        data:
          room_num: '5'
          unit_num: '1'
          control_action: 'on'
      turn_off:
        service: rest_command.light_control_room
        data:
          room_num: '5'
          unit_num: '1'
          control_action: 'off'
          
    lights_room5:
      friendly_name: "방5 조명2"
      value_template: "{{ states('sensor.lights_room5').split('\n')[1] }}"
      turn_on:
        service: rest_command.light_control_room
        data:
          room_num: '5'
          unit_num: '2'
          control_action: 'on'
      turn_off:
        service: rest_command.light_control_room
        data:
          room_num: '5'
          unit_num: '2'
          control_action: 'off'
          
          